const HTTPStatusCode = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

const DEFAULT_TIME_DELAY = 2000;

module.exports = {
  HTTPStatusCode,
  DEFAULT_TIME_DELAY,
};
